//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credits
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public int ClientID { get; set; }
        public double Amount { get; set; }
        public double InterestRate { get; set; }
        public System.DateTime IssuedDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Status { get; set; }
        public double DebtAmount { get; set; }
        public System.DateTime LastPaymentDate { get; set; }
        public System.DateTime NextPaymentDate { get; set; }
        public double LastPaymentAmount { get; set; }
        public double NextPaymentAmount { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual LoanApplications LoanApplications { get; set; }
    }
}
